/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.laboratorio;

/**
 *
 * @author fabianes
 */
public class AdminUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public AdminUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuOpc1 = new javax.swing.JButton();
        MenuOpc2 = new javax.swing.JButton();
        MenuOpc3 = new javax.swing.JButton();
        MenuOpc4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDispositivos = new javax.swing.JTable();
        inputSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        radioPrestados = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuOpc1.setBackground(new java.awt.Color(0, 102, 255));
        MenuOpc1.setForeground(new java.awt.Color(255, 255, 255));
        MenuOpc1.setText("Inicio");
        MenuOpc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpc1ActionPerformed(evt);
            }
        });
        jPanel1.add(MenuOpc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 201, 180, -1));

        MenuOpc2.setBackground(new java.awt.Color(0, 102, 255));
        MenuOpc2.setForeground(new java.awt.Color(255, 255, 255));
        MenuOpc2.setText("Dispositivo");
        MenuOpc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpc2ActionPerformed(evt);
            }
        });
        jPanel1.add(MenuOpc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 230, 180, -1));

        MenuOpc3.setBackground(new java.awt.Color(0, 102, 255));
        MenuOpc3.setForeground(new java.awt.Color(255, 255, 255));
        MenuOpc3.setText("Prestamo");
        MenuOpc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpc3ActionPerformed(evt);
            }
        });
        jPanel1.add(MenuOpc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 259, 180, -1));

        MenuOpc4.setBackground(new java.awt.Color(0, 102, 255));
        MenuOpc4.setForeground(new java.awt.Color(255, 255, 255));
        MenuOpc4.setText("Usuarios");
        MenuOpc4.setEnabled(false);
        jPanel1.add(MenuOpc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 288, 180, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/laboratorio/assets/user_.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 67, 120, 116));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 460));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDispositivos.setBackground(new java.awt.Color(102, 153, 255));
        tableDispositivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre completo", "Cédula", "Celular", "Correo", "Pendientes", "Acciones"
            }
        ));
        tableDispositivos.setGridColor(new java.awt.Color(255, 255, 255));
        tableDispositivos.setShowGrid(true);
        jScrollPane1.setViewportView(tableDispositivos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 137, 540, 91));

        inputSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSearchActionPerformed(evt);
            }
        });
        jPanel3.add(inputSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 104, 108, -1));

        jLabel1.setText("Buscar:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 107, -1, -1));

        radioPrestados.setBackground(new java.awt.Color(255, 255, 255));
        radioPrestados.setText("Mostrar pendientes");
        radioPrestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPrestadosActionPerformed(evt);
            }
        });
        jPanel3.add(radioPrestados, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 103, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel9.setText("Sistema de inventario");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 0, 570, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchActionPerformed

    private void radioPrestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPrestadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPrestadosActionPerformed

    private void MenuOpc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpc1ActionPerformed
        vista a = new vista();
        a.setVisible(true);
        a.setLayout(null);
        setVisible(false);
    }//GEN-LAST:event_MenuOpc1ActionPerformed

    private void MenuOpc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpc2ActionPerformed
        AdminDispositivos a = new AdminDispositivos();
        a.setVisible(true);
        a.setLayout(null);
        setVisible(false);
    }//GEN-LAST:event_MenuOpc2ActionPerformed

    private void MenuOpc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpc3ActionPerformed
        AdminPrestamos a = new AdminPrestamos();
        a.setVisible(true);
        a.setLayout(null);
        setVisible(false);
    }//GEN-LAST:event_MenuOpc3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuOpc1;
    private javax.swing.JButton MenuOpc2;
    private javax.swing.JButton MenuOpc3;
    private javax.swing.JButton MenuOpc4;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioPrestados;
    private javax.swing.JTable tableDispositivos;
    // End of variables declaration//GEN-END:variables
}
